appdecodeweb/appdecodeweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
#from loginapp import urls as login_urls
#from loginapp.views import *

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^user/', include('loginapp.urls', namespace="users")),
    url(r'^app/', include('userapp.urls', namespace="app")),
    #url(r'^$', 'django.contrib.auth.views.login'),
    #url(r'^logout/$', logout_page),
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
    #url(r'^register/$', register),
    #url(r'^register/success/$', register_success),
    #url(r'^home/$', home),
    url(r'^admin/', include(admin.site.urls)),
]

appdecodeweb/loginapp/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import user_passes_test

import views

login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), '/user/home')

urlpatterns = [
    url(r'^$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', views.logout_page, name='logout'),
    url(r'^accounts/login/$', login_forbidden('django.contrib.auth.views.login'), name='login'), # If user is not login it will redirect to login page
    url(r'^register/$', login_forbidden(views.register), name='register'),
    url(r'^register/success/$', views.register_success, name='register_success'),
    url(r'^home/$', views.home, name='home'),

]

appdecodeweb/userapp/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import user_passes_test

import views

login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), '/user/home')

#(?P<id>REGEXP)
urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^info/(?P<app_id>[a-zA-Z0-9._]+)/$', views.app_info, name='info'),
    url(r'^sentiment/(?P<app_id>[a-zA-Z0-9._]+)/$', views.sentiment, name='sentiment'),
    url(r'^analytics/(?P<app_id>[a-zA-Z0-9._]+)/(?P<category>[a-zA-Z0-9._]+)/$', views.analytics, name='analytics'),
    #url(r'^analytics/(?P<app_id>[a-zA-Z0-9._]+)/$', views.analytics, name='analytics'),
    url(r'^rank/(?P<app_id>[a-zA-Z0-9._]+)/$', views.app_rank, name='rank'),
    url(r'^intelligence/(?P<app_id>[a-zA-Z0-9._]+)/$', views.app_intelligence, name='intelligence'),
    url(r'^sentiment_bar/(?P<app_id>[a-zA-Z0-9._]+)/$', views.sentiment_bar, name='sentiment_bar'),
    url(r'^ratings/(?P<app_id>[a-zA-Z0-9._]+)/$', views.ratings, name='ratings'),
    url(r'^rank_plot/(?P<app_id>[a-zA-Z0-9._]+)/$', views.rank_plot, name='catrank'),
]

appdecodeweb/templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
    {% if title %}
    <title>{{ title }} - Understand Your Apps</title>
    {% else %}
    <title>AppDecode - Understand Your Apps</title>
    {% endif %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" media="screen">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static "css/foundation.css" %}">
    <style type="text/css">
        html, body {
            height: 100%;
        }
        .navbar { margin-bottom:0px !important;}
        .carousel-caption { margin-top:0px !important }
        h3 {
            font-family: GTWalsheimMedium;
            font-size: 30px;
            line-height: 38px
        }
        p {
            margin: 0 0 10px
        }
        img {
            vertical-align: middle
        }
        .btm-mrg {
            margin-bottom: 7%;
        }
        .img-responsive {
            display: block;
            max-width: 100%;
            height: auto
        }

        .img-rounded {
            border-radius: 6px
        }
        .homeads{
            margin-left: 20%;
            margin-right: 20%;
            text-align: center;
            /*#FCDFFF*/
        }
        .hometext{
            margin-top: 25px;
            left:  5%;
            text-align: left;

        }
        .loginback{
            background-image:url("{% block body_image %}{% endblock %}");
            -moz-background-size: cover;
            -webkit-background-size: cover;
            background-size: cover;
            background-position: top center !important;
            background-repeat: no-repeat !important;
            background-attachment: fixed;
        }
        .foxiehome{
            background-image:url("{% block foxie %}{% endblock %}");
            background-color: #2F83D7;
            background-repeat: no-repeat;
            background-size: auto 105%;
            background-position: center top;

        }
        .txtclr{color:white;}
        .dblock{ display: block; color: yellow;}
        .din{ display: inline;}
        .homebrag{margin: 0% 25% 0% 0%;}
        #nvc {
           color:white;
        }
    </style>
</head>
<body class="loginback">
    <nav class="navbar navbar-inverse" style="background-color: #1F3950">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>                        
        </button>
        <a id="nvc" class="navbar-brand" href="/">AppDecode</a>
    </div>

    <div class="collapse navbar-collapse" id="myNavbar">


      <ul class="nav navbar-nav">
        <li ><a id="nvc" href="{% url 'app:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
    <!--
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">Page 1 <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
        </ul>
    </li>
    <li><a href="#">Page 2</a></li>
    <li><a href="#">Page 3</a></li>
-->
</ul>
<ul class="nav navbar-nav navbar-right" style="background-color:#1C3348">
    <li><a id="nvc" href="/about"><span class="glyphicon glyphicon-info-sign"></span> About</a></li>
    <li><a id="nvc" href="/contact"><span class="glyphicon glyphicon-comment"></span> Contact</a></li>
    {% block useraction %}
    {% endblock %}
</ul>
</div>
</div>
</nav>
{% block content %}{% endblock %}
</body>
</html>

appdecodeweb/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block foxie %}/static/images/AppAnnie.png{% endblock %}
{% block useraction %}
<li>
	<a id="nvc" href="{% url 'users:register' %}">
		<span class="glyphicon glyphicon-user"></span> Sign Up
	</a>
</li>
<li>
	<a id="nvc" href="{% url 'users:login' %}">
		<span class="glyphicon glyphicon-log-in"></span> Login
	</a>
</li>
{% endblock %}
{% block content %}
<div  class="foxiehome" style="height:60%;">
	<section class="row">
		<header class="large-12 columns">
			<h2 class="txtclr" style="margin-top:7%;">Build better apps.</h2>
			<div class="txtclr">
				AppDecode delivers data and insights to succeed in the app economy.
			</div>
			<a class="btn btn-danger btn-lg" href="{% url 'users:register' %}" style="margin: 7% 7% 8% 0%;">SIGN UP, ITS FREE</a>
			<div class="dblock">
				<p class="din homebrag"><strong>7000+ Apps </br>using Analytics</strong></p>
				<p class="din homebrag"><strong>App Rankings</strong></p>
			</div>
		</header>
	</section>
</div>
<div class="homeads">
	<div class="btm-mrg">
		<h3> Market Data</h3>
		Over 300,000 people choose App Annie as their source of mobile app market data and dashboard tools, with the most comprehensive and accurate data set available on mobile apps.
	</div>
	<div class="btm-mrg">
		<img src="{% static "images/storestats.png" %}" style="float: left;top:25px;margin-right: 10%;" onload="this.width/=2.5;this.onload=null;">
		<div class="hometext">
			<h3>Store Stats</h3>
			<h5>Monitor the app ecosystem and your competitors.</h5>
			Check hourly or daily top charts as well as ranking history, search keywords and featured placements for millions of apps.
		</div>
	</div>
	<div class="btm-mrg">
		<img src="{% static "images/appstoreanal.png" %}" style="float: left;top:25px;margin-right: 10%;" onload="this.width/=2.5;this.onload=null;">
		<div class="hometext">
			<h3>Store Stats</h3>
			<h5>Monitor the app ecosystem and your competitors.</h5>
			Monitor downloads, revenue, reviews, search keywords and more across your entire app portfolio, simply organized in one dashboard and without the need for an SDK.
		</div>
	</div>
	<div class="btm-mrg">
		<img src="{% static "images/inappanal.png" %}" style="float: left;top:25px;margin-right: 10%;" onload="this.width/=2.5;this.onload=null;">
		<div class="hometext">
			<h3>In-App Analytics </h3>
			<h5>Monitor the usage metrics that matter most for your app business.
			</h5>
			Track the health of your user base by adding app usage metrics to your App Analytics dashboard. Instantly surface insights such as whether version updates impact your average session duration, or how active users correlate with revenue.
		</div>
	</div>

	<hr>

	<div class="btm-mrg">
		<img src="{% static "images/audience.png" %}" style="float: left;top:25px;margin-right: 10%;" onload="this.width/=2.5;this.onload=null;">
		<div class="hometext">
			<h3>Audience Intelligence</h3>
			<h5>Detailed data about who is using every major mobile app.</h5>
			Estimates on user demographics, cross-app adoption, and users' opinions of app quality. Get app-level data for thousands of apps to understand everything from user gender and age to income and education level.
		</div>
	</div>
	<div class="btm-mrg">
		<img src="{% static "images/usage.png" %}" style="float: left;top:25px;margin-right: 10%;" onload="this.width/=2.5;this.onload=null;">
		<div class="hometext">
			<h3>Usage Intelligence</h3>
			<h5>A revolutionary understanding of mobile app and device usage.</h5>
			Deep insights into an app's users, engagement, reach and retention. Follow daily, weekly and monthly updates on the apps you care about, broken down by app, device and country.
		</div>
	</div>
	<div class="btm-mrg">
		<img src="{% static "images/storeint.png"%}" style="float: left;top:25px;margin-right: 10%;" onload="this.width/=2.5;this.onload=null;">
		<div class="hometext">
			<h3>Store Intelligence</h3>
			<h5>Complete app store transparency on every download and dollar.</h5>
			Unparalleled insight with the most accurate estimates of app sales and revenue performance. Available for millions of apps, hundreds of thousands of companies, 155 countries and over 50 categories.
		</div>
	</div>
</div>
<div class="panel-footer text-center">
	<nav class="navbar navbar-default navbar-bottom" style="background-color:#101D29;" role="navigation">
		<div class="row">
			<div class="col-md-3">
				<ul class="nav nav-pills nav-stacked">
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
			<div class="col-md-3">
				<ul class="nav nav-pills nav-stacked">
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
				</ul>
			</div>
			<ul class="nav nav-pills nav-justified">
				<a href=""><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a>
				<a href=""><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a>
				<a href=""><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a>
				<a href=""><i id="social-em" class="fa fa-envelope-square fa-3x social"></i></a>
			</div>
			<hr/>
			<div class="row">
				<div class="col-lg-12">
					<ul class="nav nav-pills nav-justified">
						<li><a href="/">AppDecode</a></li>
					</ul>
				</div>
			</div>
		</nav>
	</div>
	{% endblock %}