appdecodeweb/appdecodeweb/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
#from loginapp import urls as login_urls
#from loginapp.views import *

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='index'),
    url(r'^user/', include('loginapp.urls', namespace="users")),
    url(r'^app/', include('userapp.urls', namespace="app")),
    #url(r'^$', 'django.contrib.auth.views.login'),
    #url(r'^logout/$', logout_page),
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
    #url(r'^register/$', register),
    #url(r'^register/success/$', register_success),
    #url(r'^home/$', home),
    url(r'^admin/', include(admin.site.urls)),
]

appdecodeweb/loginapp/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import user_passes_test

import views

login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), '/user/home')

urlpatterns = [
    url(r'^$', 'django.contrib.auth.views.login'),
    url(r'^logout/$', views.logout_page, name='logout'),
    url(r'^accounts/login/$', login_forbidden('django.contrib.auth.views.login'), name='login'), # If user is not login it will redirect to login page
    url(r'^register/$', login_forbidden(views.register), name='register'),
    url(r'^register/success/$', views.register_success, name='register_success'),
    url(r'^home/$', views.home, name='home'),

]

appdecodeweb/userapp/urls.py
from django.conf.urls import include, url
from django.contrib.auth.decorators import user_passes_test

import views

login_forbidden =  user_passes_test(lambda u: u.is_anonymous(), '/user/home')

#(?P<id>REGEXP)
urlpatterns = [
    url(r'^home/$', views.home, name='home'),
    url(r'^info/(?P<app_id>[a-zA-Z0-9._]+)/$', views.app_info, name='info'),
    url(r'^sentiment/(?P<app_id>[a-zA-Z0-9._]+)/$', views.sentiment, name='sentiment'),
    url(r'^analytics/(?P<app_id>[a-zA-Z0-9._]+)/(?P<category>[a-zA-Z0-9._]+)/$', views.analytics, name='analytics'),
    #url(r'^analytics/(?P<app_id>[a-zA-Z0-9._]+)/$', views.analytics, name='analytics'),
    url(r'^rank/(?P<app_id>[a-zA-Z0-9._]+)/$', views.app_rank, name='rank'),
    url(r'^intelligence/(?P<app_id>[a-zA-Z0-9._]+)/$', views.app_intelligence, name='intelligence'),
    url(r'^sentiment_bar/(?P<app_id>[a-zA-Z0-9._]+)/$', views.sentiment_bar, name='sentiment_bar'),
    url(r'^ratings/(?P<app_id>[a-zA-Z0-9._]+)/$', views.ratings, name='ratings'),
    url(r'^rank_plot/(?P<app_id>[a-zA-Z0-9._]+)/$', views.rank_plot, name='catrank'),
]

appdecodeweb/userapp/models.py
from django.db import models

# Create your models here.

appdecodeweb/userapp/views.py
import json
import requests
import urlparse

import pygal
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render_to_response, render
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy, reverse

from userapp.utils import *
from app_settings import API_URL
from userapp.utils import search, appdata


@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def home(request):
    """
    Home page with search feature. 
    Returns the search result after user search
    """
    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        result = search.Search().search(query_string)
        url = urlparse.urljoin(API_URL, 'api/get/app/search' + '/key/test')
        resp = requests.post(url, data=json.dumps({'ids':result}))
        #for maintaining the order of the ranking that gets lost in dict
        response = ['']*len(result)
        if isinstance(resp.json()['response'], list):
            for r in resp.json()['response']:
                r['id'] = r.pop('_id')
                response[result.index(r['id'])] = r
        return render(request, 
            'userapp/search.html',
            {'result': response})
    else:
        return render(request,
            'userapp/home.html',
            {'user': request.user},)


@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def app_info(request, app_id):
    """
        Return information of the selected app.
        In try block
        Processing to get latest top chart and category rank from india
        if top_chart rank = 0 for latest crawl get second last crawl value
    """
    country = 'in'
    url = urlparse.urljoin(API_URL, 'api/get/app/' + str(app_id) + '/key/test')
    result = appdata.AppProcessor().get_result(url, app_id)
    try:
        idx = -(result['country'][::-1].index(country)+1)
        result['category_rank'] = [result['category_rank'][idx]]
        result['topchart_rank'] = [result['topchart_rank'][idx]]
    except ValueError as err:
        print(err)
        pass
    print result['category_rank']
    if result['error']:
        return render_to_response('404.html')
    return render(request, 'userapp/admin/apphome.html', {'result': result})


@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def sentiment(request, app_id):
    """
    Returns app user's opinion. Rate the opinion as positive/negative
    """
    #basic app info
    url = urlparse.urljoin(API_URL, 'api/get/app/' + str(app_id) + '/key/test')
    result = appdata.AppProcessor().get_result(url, app_id)
    surl = urlparse.urljoin(API_URL, 'api/get/app/rate/' + str(app_id) + '/key/test')
    static_dir = settings.STATICFILES_DIRS[0]
    Process = appdata.AppProcessor()
    Process.word_cloud(app_id, surl, static_dir)
    return render(request, 'userapp/admin/sentiment.html', {'result': result})


@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def app_rank(request, app_id):
    """
    return the app rank history. Rank for different countries.
    Rightnow it is only for India
    """
    url = urlparse.urljoin(API_URL, 'api/get/app/' + str(app_id) + '/key/test')
    result = appdata.AppProcessor().get_result(url, app_id)
    return render(request, 'userapp/admin/apprank.html', {'result': result})


@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def app_intelligence(request, app_id):
    """Intelligence:
    1. Similar apps performance data
    """
    url = urlparse.urljoin(API_URL, 'api/get/app/' + str(app_id) + '/key/test')
    result = appdata.AppProcessor().get_result(url, app_id)
    result['similar'] = [r.split('id=')[-1] for r in result['similar']]
    return render(request, 'userapp/admin/intelligence.html', {'result': result})

@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def analytics(request, app_id, category):
    """General app analytics details"""
    result = {}
    for typ in ['free', 'paid']:
        url = urlparse.urljoin(API_URL, 'api/get/top/category/' + str(category).capitalize() + '/{}/key/test').format(typ)
        result['{}'.format(typ)] = appdata.AppProcessor().get_top_cat(url, category)
    url = urlparse.urljoin(API_URL, 'api/get/app/' + str(app_id) + '/key/test')
    data = appdata.AppProcessor().get_result(url, app_id)
    result['icon'] = data['icon']
    result['app_name'] = data['app_name']
    result['id'] = app_id
    result['category'] = [category]
    return render(request, 'userapp/admin/analytics.html', {'result': result})
    
  ####################
 #Plotting EndPoints#
####################

@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def sentiment_bar(request, app_id):
    """Bar graph of sentiment percentage +ve and -ve"""
    url = urlparse.urljoin(API_URL, 'api/get/app/rate/' + str(app_id) + '/key/test')
    result = appdata.AppProcessor().get_result(url, app_id)
    bar_chart = pygal.Bar(height=300, width=400, show_y_labels=False, 
        show_legend=False)
    bar_chart.title = "Sentiments"
    
    try:
        lower, params = [result['n_percent']*100, result['p_percent']*100], ["Positive", "Negative"]
    except TypeError as err:
        print (err)
        lower, params = [], ["Positive", "Negative"]

    bar_chart.add('Percentage(%)', lower)
    bar_chart.x_labels = params
    return HttpResponse(bar_chart.render(), content_type='image/svg+xml')


@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def ratings(request, app_id):
    """
    Returns a bar chart of app ratings
    """
    #get the app latest ratings
    resp = requests.get('http://127.0.0.1:5000/api/get/app/ratings/{}/key/test'.format(app_id) )
    score = resp.json()[app_id]['score'][-1]
    bar_chart = pygal.HorizontalBar(
        width=450 ,
        height=360, 
        show_x_labels=False, 
        show_legend=False)
    bar_chart.title = "Ratings"
    lower,params = [score[stars] for stars in ['OneStars', 'TwoStars', 'ThreeStars', 'FourStars', 'FiveStars']],['1','2','3','4','5']
    bar_chart.add('Stars', lower)
    #bar_chart.add('higher', higher)
    bar_chart.x_labels = params
    return HttpResponse(bar_chart.render(), content_type='image/svg+xml')


@login_required(login_url=reverse_lazy('users:login'), redirect_field_name=None)
def rank_plot(request, app_id):
    url = urlparse.urljoin(API_URL, 'api/get/app/rank/' + str(app_id) + '/key/test')
    Process = appdata.AppProcessor()
    result = Process.get_result(url, app_id)
    ranks = Process.get_ranks()

    #a gap of .10 between major and hide minor
    date_chart = pygal.Line( 
        legend_at_bottom=True,
        legend_box_size=10,
        x_label_rotation=20, 
        show_minor_y_labels=False)#, y_labels_major_every=)
    date_chart.x_labels = ranks[2][-20:]
    #y = range(0, max(ranks[0]) if max(ranks[0])>max(ranks[1]) else max(ranks[1]))
    #print y
    #date_chart.y_labels = y
    date_chart.add("Global", ranks[1][-20:])
    date_chart.add("Category", ranks[0][-20:])
    return HttpResponse(date_chart.render(), content_type='image/svg+xml')

appdecodeweb/userapp/templates/userapp/admin/adminbase.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>AppDecode - Understand Your Apps</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/sb-admin.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static "font-awesome/css/font-awesome.min.css" %}" rel="stylesheet" type="text/css">

    <style type="text/css">
        div {
            overflow:hidden;
        }
    </style>

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">AppDecode</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ user.username  }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="{% url 'users:logout' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li align="middle">
                        <img width="60%" height="60%" src="{{ result.icon }}"/>
                        <small style="color:white; display: block; margin: 15px 2px 10px 2px;">{{ result.app_name }}</small>
                    </li>
                    <li class="active">
                        <a href="{% url 'app:info' result.id %}"><i class="fa fa-fw fa-dashboard"></i> Details</a>
                    </li>
                    <li>
                        <a href="{% url 'app:rank' result.id %}"><i class="fa fa-fw fa-bar-chart-o"></i> Rank History </a>
                    </li>
                    <li>
                        <a href="{% url 'app:sentiment' result.id %}"><i class="fa fa-fw fa-table"></i> Review Sentiments </a>
                    </li>
                    <li>
                        <a href="{% url 'app:intelligence' result.id %}"><i class="fa fa-fw fa-edit"></i> App Intelligence</a>
                    </li>
                    <li>
                        <a href="{% url 'app:sentiment' result.id %}"><i class="fa fa-fw fa-desktop"></i> Reviews</a>
                    </li>
                    <li>
                        <a href="{% url 'app:analytics' app_id=result.id category=result.category.0 %}"><i class="fa fa-fw fa-desktop"></i> Analytics</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            {{ result.app_name }} <small>Overview</small>
                        </h1>
                    </div>
                </div>

                <!-- /.row -->
                {% block content %}
                {% endblock %}

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->

    <script src="{% static "js/jquery.js" %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>

</html>

appdecodeweb/userapp/templates/userapp/admin/analytics.html
{% extends 'userapp/admin/adminbase.html' %}
{% block content %}

<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-primary">
			<a href="{% url 'app:info' result.free.id %}">
				<div class="panel-heading">
					<div class="row">
						<div class="col-xs-6">
							<img width="60%" height="60%" src="{{ result.free.icon }}"/>
						</div>
						<div class="col-xs-6 text-right">
							<div style="font-size:15px;">{{ result.free.app_name|default_if_none:""  }}</div>
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<span class="pull-left">Top Free App in {{ result.category|last }}</span>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-green">
			<a href="{% url 'app:info' result.paid.id %}">
				<div class="panel-heading">
					<div class="row">
						<div class="col-xs-6">
							<img width="60%" height="60%" src="{{ result.paid.icon }}"/>
						</div>
						<div class="col-xs-6 text-right">
							<div style="font-size:15px;">{{ result.paid.app_name|default_if_none:""  }}</div>
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<span class="pull-left">Top Paid App in {{ result.category|last }}</span>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-yellow">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-6">
						<i class="fa fa-shopping-cart fa-5x"></i>
					</div>
					<div class="col-xs-6 text-right">
						<div class="huge">{{ result.ratings|last|default_if_none:"-"  }}</div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<span class="pull-left">Ratings</span>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel panel-red">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-6">
						<i class="fa fa-support fa-5x"></i>
					</div>
					<div class="col-xs-6 text-right">
						<small> {{ result.installs|last|default_if_none:"-"  }}</small>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<span class="pull-left">Installs</span>
				</div>
			</a>
		</div>
	</div>
</div>

{% endblock %}

appdecodeweb/userapp/templates/userapp/admin/apprank.html
{% extends 'userapp/admin/adminbase.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Area Chart</h3>
            </div>
            <div class="panel-body">
                <figure >
                    <embed type="image/svg+xml" src="{% url 'app:catrank' result.id %}"/>
                </figure>
            </div>
        </div>
    </div>
</div>

{% endblock %}

appdecodeweb/userapp/templates/userapp/admin/intelligence.html
{% extends 'userapp/admin/adminbase.html' %}
{% block content %}
<style type="text/css">
	#myModal .modal-dialog  {
		width:900px;
		overflow:hidden;
	}

</style>
<div style="margin:0 0 20px 0;">
<h3 style="color:green;" align="center">How Similar Apps are Performing?</h3>
</div>
<div class="row">
	{% for r in result.similar %}
	<div class="col-md-6">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title" style="display:inline;"><i class="fa fa-bar-chart-o fa-fw"></i>
					<a href="{% url 'app:info' r %}">{{ r }}</a>
				</h3>
				<button id="{{ r }}" type="button" style="float:right;" class="btn btn-info btn-sm" data-toggle="modal" onclick="reply_click(this.id)" data-target="#myModal">Expand</button>
			</div>
			<div class="panel-body" id="myDiv" >
				<figure >
					<embed type="image/svg+xml" src="{% url 'app:catrank' r %}"/>
				</figure>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
	<div class="modal-dialog model-lg">

		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Plot</h4>
			</div>
			<div class="modal-body">
				<p>
					<figure >
						<embed id="mod-data" type="image/svg+xml"/>
					</figure></p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>

		</div>
	</div>
	<script type="text/javascript">
		function reply_click(clicked_id){
			var graph = document.getElementById('mod-data');
			var source = "{% url 'app:catrank' 'id' %}"
			source = source.replace('id', clicked_id);
			graph.src = source;
		};
	</script>
	{% endblock %}

appdecodeweb/userapp/templates/userapp/admin/senti.html
{% extends 'userapp/admin/adminbase.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Area Chart</h3>
            </div>
            <div class="panel-body">
                <figure >
                    <embed type="image/svg+xml" src="{% url 'app:sentiment_bar' result.id %}"/>
                </figure>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Positive Cloud</h3></div>
            <div class="panel-body">
                <img height="100%" width="100%" src="/static/pos.png"/>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Negative Cloud</h3></div>
            <div class="panel-body">
                <img height="100%" width="100%" src="/static/neg.png"/>
            </div>
        </div>
    </div>
</div>

{% endblock %}

appdecodeweb/userapp/templates/userapp/admin/sentiment.html
{% extends 'userapp/admin/adminbase.html' %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Area Chart</h3>
            </div>
            <div class="panel-body">
                <figure >
                    <embed type="image/svg+xml" src="{% url 'app:sentiment_bar' result.id %}"/>
                </figure>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Positive Cloud</h3></div>
            <div class="panel-body">
                <img height="100%" width="100%" src="/static/pos.png"/>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> Negative Cloud</h3></div>
            <div class="panel-body">
                <img height="100%" width="100%" src="/static/neg.png"/>
            </div>
        </div>
    </div>
</div>

{% endblock %}